### ISSUE TITLE
linking qt5

### ISSUE THREAD

**Issue by reafrancesco** [robotology/attention#2]
@drdanz: How should I correctly link qt5 in the structure of robotology/attention?

Currently I get the following error: 
_CMake Error at src/guis/selAttentionGui/CMakeLists.txt:5 (include):
   include could not find load file:

```
 iCubUseQt5_
```

In my opinion I am missing one CMakeLists line that prevents me from loading correctly all the variables.
Any idea?
Thanks

**Comment by drdanz** [comment]
You are missing the iCubUseQt5.cmake file see https://github.com/robotology/icub-main/blob/master/conf/iCubUseQt5.cmake
